group_name=joshgav-profilesapp-group
location=westus2

cosmosdb_account_name=joshgavprofilesapp
cosmosdb_db_name=profilesapp
cosmosdb_collection_name=profiles

storage_account_name=joshgavprofilesappstor
storage_container_name=pictures

directory_app_name=joshgav-profiles-app
directory_app_identifier="https://${directory_app_name}"
